import { UserProvider } from "@/context/UserContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rewarding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <main
            className="flex items-center min-h-screen bg-neutral-950 flex-col gap-2 relative overflow-hidden
        after:rounded-full z-10 py-4"
          >
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
